### ISSUE TITLE
Cilium cannot install on Amazon EKS because cluster name is not valid

### ISSUE THREAD

**Issue by MartinDeLaTorre** [cilium/cilium-cli#1196]
## Bug report

**General Information**

- Cilium CLI version:
```
$ cilium version
cilium-cli: v0.12.2 compiled with go1.19 on linux/amd64
cilium image (default): v1.12.1
cilium image (stable): v1.12.3
cilium image (running): unknown. Unable to obtain cilium version, no cilium pods found in namespace "kube-system"
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
```
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)
I am using [AWS EKS](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html)
- Link to relevant artifacts (policies, deployments scripts, ...)
EKS support is specifically documented in the [Quick Installation Guide](https://docs.cilium.io/en/v1.12/gettingstarted/k8s-install-default/) which is why I believe this to be a bug.
- Generate and upload a system zip: `cilium sysdump`
[cilium-sysdump-20221107-115607.zip](https://github.com/cilium/cilium-cli/files/9954258/cilium-sysdump-20221107-115607.zip)

**How to reproduce the issue**

1. Set up an EKS Cluster: https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html
`eksctl create cluster --name my-medium-eksctl-cluster-2 --region us-east-2 --node-type t3.medium --profile <your-AWS-CLI-profile>` (If you have a default profile set up in your AWS CLI, you can remove `--profile <your-AWS-CLI-profile>`)
2. Use the AWS CLI to update your `~/.kube/config` file: `aws eks --region us-east-2 update-kubeconfig --name my-medium-eksctl-cluster-2 --profile <your-AWS-CLI-profile>` (Again, If you have a default profile set up in your AWS CLI, you can remove `--profile <your-AWS-CLI-profile>`)
3. Do `cilium install`
```
$ cilium install
🔮 Auto-detected Kubernetes kind: EKS
ℹ️  Using Cilium version 1.12.1
🔮 Auto-detected cluster name: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2
🔮 Auto-detected datapath mode: aws-eni
❌ Cluster name "arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2" is not valid, must match regular expression: ^[a-z0-9]([-a-z0-9]*[a-z0-9])$
↩️ Rolling back installation...

Error: Unable to install Cilium: invalid cluster name
```

I know that the name I put "my-medium-eksctl-cluster-2" matches the regex just fine: https://regex101.com/r/tpI37n/1
But obviously Amazon puts some extra info in the ARN and puts a bunch of colons that cilium can't parse.

I tried various workarounds to rename the cluster in my `~/.kube/config` file, but I couldn't get it to work: when I manually modified the config file then kubectl wouldn't be able to connect to the cluster and would keep trying to connect to localhost.

Any workarounds? Or perhaps you could direct me to where in the source code cilium parses the `~/.kube/config` file so I can modify it?

Related Issues:
* https://github.com/cilium/cilium-cli/issues/797
* https://github.com/cilium/cilium-cli/issues/696

-----
Edit:
I think I found the culprit:
https://github.com/cilium/cilium-cli/blob/094b30b4fa383d4158278f62d321c43f139ca403/install/autodetect.go#L35

It took me a bit because I was searching in [https://github.com/cilium/cilium](https://github.com/cilium/cilium) not realizing that [https://github.com/cilium/cilium-cli](https://github.com/cilium/cilium-cli) is a different repository.

**Comment by MartinDeLaTorre** [comment]
I think I found the culprit:
https://github.com/cilium/cilium-cli/blob/094b30b4fa383d4158278f62d321c43f139ca403/install/autodetect.go#L35

It took me a bit because I was searching in [https://github.com/cilium/cilium](https://github.com/cilium/cilium) not realizing that [https://github.com/cilium/cilium-cli](https://github.com/cilium/cilium-cli) is a different repository.

**Comment by martinhitachi** [comment]
Nevermind, I figured out how to rename a cluster by modifying the kubectl config.

I first did a little studying to better understand the kube config YAML file (`~/.kube/config`), specifically by learning [the difference between Contexts & Clusters](https://stackoverflow.com/questions/56299440/kubectl-context-vs-cluster)

AWS CLI just uses the ARN number for everything: the cluster name, the context name, and the user name.
I think what was happening before is that I was messing up the users when I tried to manually edit the YAML file.

To rename your cluster by editing the `~/.kube/config` YAML file, you'll need to change it in 2 places:
```
clusters:
- cluster:
    certificate-authority-data: <gobeldy gook>
    server: https://my-minikube-cluster.com
  name: my-cluster-1
- cluster:
    certificate-authority-data: <more gobeldy gook>
    server: https://my-kind-cluster.com
  name: my-cluster-2
- cluster:
    certificate-authority-data: <more gobeldy gook>
    server: https://my-eks-cluster-2.amazonaws.com
  name: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # Change this line
contexts:
- context:
    cluster: my-cluster-1
    user: user-1
  name: my-context-1
- context:
    cluster: my-cluster-2
    user: user-2
  name: my-context-2
- context:
    cluster: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # Change this line
    user: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  name: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  current-context: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  ```
  
  Also, DONT touch anything in the `users:` part of the yaml file, and don't mess with the `contexts: - context: user: <username>`. The <username> is probably set as your cluster's ARN number. You don't need to modify it, so don't.
  
  Afterwards it should look like this:
  ```
clusters:
- cluster:
    certificate-authority-data: <gobeldy gook>
    server: https://my-minikube-cluster.com
  name: my-cluster-1
- cluster:
    certificate-authority-data: <more gobeldy gook>
    server: https://my-kind-cluster.com
  name: my-cluster-2
- cluster:
    certificate-authority-data: <more gobeldy gook>
    server: https://my-eks-cluster-2.amazonaws.com
  name: my-medium-eksctl-cluster-2 # Changed
contexts:
- context:
    cluster: my-cluster-1
    user: user-1
  name: my-context-1
- context:
    cluster: my-cluster-2
    user: user-2
  name: my-context-2
- context:
    cluster: my-medium-eksctl-cluster-2 # Changed
    user: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  name: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  current-context: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  ```

**Comment by MartinDeLaTorre** [comment]
Nevermind, I figured out how to rename a cluster by modifying the kubectl config.

I first did a little studying to better understand the kube config YAML file (`~/.kube/config`), specifically by learning [the difference between Contexts & Clusters](https://stackoverflow.com/questions/56299440/kubectl-context-vs-cluster)

AWS CLI just uses the ARN number for everything: the cluster name, the context name, and the user name.
I think what was happening before is that I was messing up the users when I tried to manually edit the YAML file.

To rename your cluster by editing the `~/.kube/config` YAML file, you'll need to change it in 2 places:
```
clusters:
- cluster:
    certificate-authority-data: <gobeldy gook>
    server: https://my-minikube-cluster.com
  name: my-cluster-1
- cluster:
    certificate-authority-data: <more gobeldy gook>
    server: https://my-kind-cluster.com
  name: my-cluster-2
- cluster:
    certificate-authority-data: <more gobeldy gook>
    server: https://my-eks-cluster-2.amazonaws.com
  name: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # Change this line
contexts:
- context:
    cluster: my-cluster-1
    user: user-1
  name: my-context-1
- context:
    cluster: my-cluster-2
    user: user-2
  name: my-context-2
- context:
    cluster: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # Change this line
    user: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  name: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  current-context: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  ```
  
  Also, DONT touch anything in the `users:` part of the yaml file, and don't mess with the `contexts: - context: user: <username>`. The <username> is probably set as your cluster's ARN number. You don't need to modify it, so don't.
  
  Afterwards it should look like this:
  ```
clusters:
- cluster:
    certificate-authority-data: <gobeldy gook>
    server: https://my-minikube-cluster.com
  name: my-cluster-1
- cluster:
    certificate-authority-data: <more gobeldy gook>
    server: https://my-kind-cluster.com
  name: my-cluster-2
- cluster:
    certificate-authority-data: <more gobeldy gook>
    server: https://my-eks-cluster-2.amazonaws.com
  name: my-medium-eksctl-cluster-2 # Changed
contexts:
- context:
    cluster: my-cluster-1
    user: user-1
  name: my-context-1
- context:
    cluster: my-cluster-2
    user: user-2
  name: my-context-2
- context:
    cluster: my-medium-eksctl-cluster-2 # Changed
    user: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  name: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  current-context: arn:aws:eks:us-east-2:674167431508:cluster/my-medium-eksctl-cluster-2 # DONT change this line
  ```
