### ISSUE TITLE
Multiple Websites with single ipaddress

### ISSUE THREAD

**Issue by pranaypathik** [cilium/cilium-cli#1363]
**Current Setup**
Installed CILIUM on AKS using BYO CNI. Installed cilium via helm template.

We have two websites (name changed) which resolves to the **SAME** ip-address
site1.somedomain.com
site2.somedomain.com

Below is an example of policy to restrict traffic to site1.somedomain.com

```YAML
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn"
  namespace: site1  
spec:
  endpointSelector: {}
  egress:
  - toFQDNs:
      - matchName: site1.somedomain.com
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
```

**Expected Result**
container in site1 namespace should be able to connect to site1.somedomain.com
container in site1 namespace should **not** be able to connect to site2.somedomain.com

**Testing Result**
From the container is site1 namespace, I was able to connect to both site1.somedomain.com and site2.somedomain.com
Confirmed it was not able to reach out to any external site ie apart from site1.somedomain.com and site2.somedomain.com

*Issue summary*
container1 in site1 namespace should not be able to connect to site2.domain.com.

**Research**
I check github and slack and I did not see any similar problem reported.
As per cilium documentation it seems like it has a DNS cache and it uses the IP address for policy enforcement which may explain this behaviour

**help Required**
Need confirmation/assistance on how this policy enforcement can be achieved using Cilium
