### ISSUE TITLE
`hubble enable` doesn't set hubble-metrics port in Cilium agent

### ISSUE THREAD

**Issue by lambdanis** [cilium/cilium-cli#1422]
## Bug report

Running a command enabling Hubble and Hubble metrics, e.g.:
```
cilium hubble enable --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
results in a `hubble-metrics` service being created:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9965"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: hubble
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble
  name: hubble-metrics
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: hubble-metrics
    port: 9965
    protocol: TCP
    targetPort: hubble-metrics
  selector:
    k8s-app: cilium
  type: ClusterIP
```
but doesn't set `hubble-metrics` port in Cilium daemonset. That means that `hubble-metrics` Endpoints object doesn't get populated with Cilium pods IPs. Prometheus service discovery often relies on Endpoints objects, so Prometheus won't scrape Hubble metrics in that case.

If you enable Hubble metrics on `cilium install`:
```
cilium install --version="1.13.0" --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
then `hubble-metrics` port is configured. But from the user perspective it makes sense to enable Hubble metrics when enabling Hubble:
```
cilium install
cilium hubble enable --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
and then metrics are exposed, but `hubble-metrics` port is not configured.

A "proper" solution for this issue would be using Helm commands for all installs/updates (cilium/cilium-cli#1396). Meanwhile, a "hack" solution would be updating cilium daemonset in addition to other components on `hubble enable`.

**General Information**

- Cilium CLI version: v0.12.13
- Orchestration system version in use: k8s 1.24.7
- Platform / infrastructure information: Kind

**How to reproduce the issue**

```
cilium install --version="1.13.0"
cilium hubble enable --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
