### ISSUE TITLE
Proposal / RFE: Change to use the value of `external-dns.alpha.kubernetes.io/hostname` instead of `${ClusterName}.mesh.cilium.io` when `external-dns.alpha.kubernetes.io/hostname` is set on the `clustermesh-apiserver` LoadBalancer Service

### ISSUE THREAD

**Issue by kahirokunn** [cilium/cilium-cli#1539]
## Proposal / RFE

In the current implementation, it is necessary to perform a DNS lookup for all target clusters in the environment running `cilium clustermesh connect`. This can be difficult depending on network configurations.

As a security best practice, the `clustermesh-apiserver` NLB should be created in a private subnet. However, the default hostname's A record for an NLB in a private subnet is registered in the `Route53 Private Hosted Zone`. As a result, lookup from a local PC will fail.

The primary solution is to create a custom A record for the `clustermesh-apiserver` NLB using tools like `External DNS`, and register it in a Public Hosted Zone.

![image](https://user-images.githubusercontent.com/22343391/234726650-b304ba37-7e3f-48ee-960f-0b43f99a5476.png)

However, the primary reason for performing the DNS lookup is to set the IP for `hostAliases` of `${ClusterName}.mesh.cilium.io`. The initial motivation for wanting to perform a DNS lookup during the `cilium clustermesh connect` process is when the DNS hostname of the `clustermesh-apiserver` LoadBalancer Service is unknown, right?

## Implementation Pattern 1

As a solution, how about adding the following flags?

* `--use-status-hostname`
  * Referencing `status.loadBalancer.ingress[].hostname`
* `--use-destination-status-hostname`
  * Referencing `status.loadBalancer.ingress[].hostname`
* `--use-externaldns-hostname`
  * Referencing `metadata.annotations."external-dns.alpha.kubernetes.io/hostname"`
* `--use-destination-externaldns-hostname`
  * Referencing `metadata.annotations."external-dns.alpha.kubernetes.io/hostname"`

In this case, there will be no need for `hostAliases` and they will not be set.
There is also a rollOutCiliumPods option in the helm values, so we think that those who want to restart the system should activate it.

## Implementation Pattern 2

1. If `external-dns.alpha.kubernetes.io/hostname` is set on `clustermesh-apiserver`, use that hostname as the target `clustermesh-apiserver` for the connection. Do not set hostAliases.
https://github.com/cilium/cilium-cli/blob/9c3ea4c5e55ee7b6d466c57ade34091e0314b13a/clustermesh/clustermesh.go#L648

2. If `metadata.annotations."external-dns.alpha.kubernetes.io/hostname"` is not set on `clustermesh-apiserver`, follow the existing process.

3. If the DNS lookup fails, reference `status.loadBalancer.ingress[].hostname` and do not set hostAliases.

There is also a rollOutCiliumPods option in the helm values, so we think that those who want to restart the system should activate it.

**Comment by asauber** [comment]
Hi, thanks for your proposal. I do think that it's important that we support LoadBalancers in private subnets for `cilium clustermesh connect`. In some cases, the user of `cilium clustermesh connect` will be on a VPN which is capable of using the cloud provider's private DNS resolvers such that the CLI will be able to resolve such hostnames. However, that is certainly not possible in all cases.

I am currently working on a reimplementation of `cilium clustermesh connect` that will replace much of the templating logic that you have come across with usage of the recently expanded-upon Helm template functions related to Clustermesh configuration and configuration of the `clustermesh-apiserver` etcd servers. For example, here is the template function that allows us to specify an arbitrary set of endpoint names or endpoint IPs for the clustermesh. There is [this function](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/clustermesh-config/_helpers.tpl#L1) to template the value of the `endpoints:` array, which is invoked for each configured cluster [here](https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/templates/clustermesh-config/clustermesh-secret.yaml#L9)

Once this has been implemented, one way to achieve the behavior that you are after would be to specify the cluster endpoints in a minimal helm values file when using the clustermesh connect command. For example:

```
cat << EOF >clustermesh-values.yaml
clustermesh:
   config:
     enabled: true
     clusters:
     - name: cluster-1
       address: cluster1.mesh.cilium.io
     - name: cluster-2
       address: cluster2.mesh.cilium.io
EOF
cilium clustermesh connect --helm-values custermesh-values.yaml
```

In this case we are using helm values to provide the addresses, and other values such as the port numbers and PKI information will be autoconfigured as usual.

In your proposal, you have two implementation paths where ExternalDNS annotations would be used. Would the user provide the value of these annotations at "connect" time, or would we expect a multi-pass workflow, where the user attempts to have these LoadBalancers created, and then annotates them?

Either way, I think the new implementation will support your intended use case, as you will be able to annotate your LoadBalancers as desired, and then use an address configuration like the above.

My current feeling is that the Cilium CLI should not attempt to write or read ExternalDNS annotations until we find that is absolutely necessary to provide a smooth configuration experienc here.

If you wouldn't mind waitig until I put up the new implementation of clustermesh connect, I would be thrilled to have you test it out and ensure that it supports this use case.

**Comment by kahirokunn** [comment]
@asauber 

> In your proposal, you have two implementation paths where ExternalDNS annotations would be used. Would the user provide the value of these annotations at "connect" time, or would we expect a multi-pass workflow, where the user attempts to have these LoadBalancers created, and then annotates them?

This is neither of the options mentioned. Annotations are applied simultaneously during the initial creation process. For example, I am deploying Cilium in an EKS environment using the `helm install` command. The values related to the clustermesh-apiserver I'm using during this process are as follows:

```yaml
clustermesh:
  apiserver:
    affinity: null
    podDisruptionBudget:
      enabled: true
    priorityClassName: system-cluster-critical
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 1024M
      requests:
        cpu: 100m
        memory: 64Mi
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        external-dns.alpha.kubernetes.io/hostname: "cilium-clustermesh-apiserver.example.com"
      externalTrafficPolicy: Local
      type: LoadBalancer
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
  useAPIServer: true
```
