### ISSUE TITLE
ipv6 connectivity tests introduced externalip pings

### ISSUE THREAD

**Issue by sergeyshevch** [cilium/cilium-cli#1608]
## Bug report

https://github.com/cilium/cilium-cli/pull/1390 introduced iteration over the node.Status.Addresses that contain not only InternalIp. In my case (AWS EKS) it contains the next info

```
addresses:
  - address: 10.3.2.189
    type: InternalIP
  - address: (ExternalNodeIP)
    type: ExternalIP
  - address: ip-10-3-2-189.ec2.internal
    type: InternalDNS
  - address: ip-10-3-2-189.ec2.internal
    type: Hostname
  - address: (ExternalNodeHostname)
    type: ExternalDNS
```

Pods in my network has no connectivity to node external IP. So tests always failing

**General Information**

- Cilium CLI version (run `cilium version`) any version 0.13+
   ```
   cilium-cli: v0.14.2 compiled with go1.20.2 on darwin/arm64
   cilium image (default): v1.13.2
   cilium image (stable): v1.13.2
   cilium image (running): v1.13.2
   ```
- Orchestration system version in use (e.g. `kubectl version`, ...) 
   ```
   Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0",    
   GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", 
   GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
   Kustomize Version: v4.5.7
   Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.2-eks-a59e1f0", 
   GitCommit:"8b68f4b95d7121d039ceebd30870e48acc7772e4", GitTreeState:"clean", BuildDate:"2023-03-09T19:59:45Z", 
   GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
   ```
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions) AWS EKS 1.26
- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip: `cilium sysdump`

**How to reproduce the issue**

1. Create EKS Cluster with nodes in public subnets
2. Run cilium connectivity tests
