### ISSUE TITLE
Cannot enable Hubble due to missing hubble-server-certs

### ISSUE THREAD

**Issue by rwunderer** [cilium/cilium-cli#1718]
## Bug report

**General Information**

- Cilium CLI version:
```
$ cilium version
cilium-cli: v0.14.6 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.13.3
cilium image (stable): v1.13.3
cilium image (running): v1.13.2
```
- Orchestration system version in use: 
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:42Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Platform / infrastructure information: `Upcloud managed K8S`, `Scaleway managed K8S`

**How to reproduce the issue**

When trying to enable hubble on a managed cluster with cilium pre-installed  `cilium hubble enable` completes without errors. However the resulting `hubble-relay` is unable to talk to the `cilium` pods as the secret `hubble-server-certs` has not been created.

This seems to be on purpose [1,2] though it's not apparent why creating these certs would amount to a bad UX?

[1] https://github.com/cilium/cilium-cli/blob/03a452f9f224c1523375de8a29ae2074524a17f8/hubble/relay.go#L184-L188
[2] https://github.com/cilium/cilium-cli/blob/03a452f9f224c1523375de8a29ae2074524a17f8/hubble/relay.go#L193-L207

**Workaround**

A rather convoluted workaround is to clone `cilium-ca` into a certmanager CA and use that for generating the missing secret. (See below; the additional secret is needed because certmanager has its own opinion on how these fields should be named). After this everything works perfectly. 

```
---
apiVersion: v1
kind: Secret
metadata:
  name: cilium-ca-for-certmanager
  namespace: kube-system
data:
  tls.crt: <ca.crt value from cilium-ca secret>
  tls.key: <ca.key value from cilium-ca-secret>
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cilium-ca
  namespace: kube-system
spec:
  ca:
    secretName: cilium-ca-for-certmanager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-server-certs
  namespace: kube-system
spec:
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: cilium-ca
  secretName: hubble-server-certs
  commonName: "*.default.hubble-grpc.cilium.io"
  dnsNames:
  - "*.default.hubble-grpc.cilium.io"
  duration: 26280h0m0s
```

I would expect cilium-cli to simply create this secret if it doesn't exist.
