### ISSUE TITLE
cilium v0.16.17 install immediately returns strconv.ParseUint: parsing "": invalid syntax

### ISSUE THREAD

**Issue by jacoboldroyduvu** [cilium/cilium-cli#2802]
**General Information**
Cilium Version

> $ cilium version
> cilium-cli: v0.16.17 compiled with go1.23.1 on linux/amd64
> cilium image (default): 
> cilium image (stable): v1.16.1
> cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found

Kubernetes version

> $ kubectl version
> Client Version: v1.28.14
> Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
> Server Version: v1.28.14

Platform info
Kubernetes installation using kubeadm on debian 12

> $ cat /etc/*release
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"

Cluster was provisioned using this kubeadm.yaml
```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: ***************
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: prod-ctrl01
  taints: null
skipPhases:
  - addon/kube-proxy
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: prod
certificatesDir: /etc/kubernetes/pki
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kubernetesVersion: v1.28.14
networking:
  dnsDomain: cluster.local
  serviceSubnet: 172.30.0.0/16
  podSubnet: 172.31.0.0/16
controlPlaneEndpoint: "<myFqdnDNSRecord>:6443"
scheduler: {}
apiServer:
  timeoutForControlPlane: 4m0s
  certSANs:
    - <myFqdnDNSRecord>
```

Steps to reproduce.

Once cluster was provisioned using kubeadm. without kube-proxy. I've downloaded the ciliumcli using the following script:
```
	CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
	CLI_ARCH=amd64
	if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
	curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
	sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
	sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
	rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
```
Attempting to run  `cilium install` immediately returns:
> strconv.ParseUint: parsing "": invalid syntax

Link so sysdump:
[cilium-sysdump-20240918-211107.zip](https://github.com/user-attachments/files/17053137/cilium-sysdump-20240918-211107.zip)

Reverting to cilium v0.16.16 allows for installation.
```bash
wget https://github.com/cilium/cilium-cli/releases/download/v0.16.16/cilium-linux-amd64.tar.gz
```
