### ISSUE TITLE
HTTP listener stops working once I add HTTPS listener

### ISSUE THREAD

**Issue by AurimasNav** [cilium/cilium-cli#2898]
## Bug report

**General Information**

It seems that once I add HTTPS listener the HTTPRoute depending on HTTP listener stops working. This prevents cert-manager issuing certificates for https using http01 solver (and dns solver does not work with our .internal domain).

- Cilium CLI version (run `cilium version`)

```shell
cilium-cli: v0.16.21 compiled with go1.23.4 on darwin/arm64
cilium image (default): v1.16.4
cilium image (stable): v1.16.5
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found
```

- Orchestration system version in use (e.g. `kubectl version`, ...)

```shell
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.30.6+k3s1
``` 
 
- Platform / infrastructure information (e.g. AWS / Azure / GCP, image / kernel versions)
 
k3s
Ubuntu 6.8.0-49.49-generic 6.8.12 
 
**How to reproduce the issue**

1. Create gateway with http listener

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: cilium
spec:
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 10.10.0.33
  gatewayClassName: cilium
  listeners:
  - name: http-solver
    protocol: HTTP
    port: 80
    allowedRoutes:
        namespaces:
          from: All
```

2. create HTTPRoute

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world-http
spec:
  hostnames:
  - hello-world.onprem.internal
  parentRefs:
  - name: internal
    namespace: cilium
    sectionName: http-solver
  rules:
  - backendRefs:
    - name: hello-world
      port: 80
``` 

3. verify that httproute is working:

```shell
curl -I http://hello-world.onprem.internal

HTTP/1.1 200 OK
accept-ranges: bytes
content-length: 1395
content-type: text/html; charset=utf-8
last-modified: Tue, 22 Jun 2021 05:40:33 GMT
date: Fri, 20 Dec 2024 17:21:17 GMT
x-envoy-upstream-service-time: 0
server: envoy

```

describe httproute

```yaml
Name:         hello-world-http
Namespace:    hello-world
Labels:       app=hello-world
              environment=dev
              tier=backend
Annotations:  argocd.argoproj.io/tracking-id: hello-world:gateway.networking.k8s.io/HTTPRoute:hello-world/hello-world-http
API Version:  gateway.networking.k8s.io/v1
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2024-12-20T16:39:38Z
  Generation:          1
  Resource Version:    3864805
  UID:                 2a7b4144-c397-42ad-a47b-88859e99b309
Spec:
  Hostnames:
    hello-world.onprem.internal
  Parent Refs:
    Group:         gateway.networking.k8s.io
    Kind:          Gateway
    Name:          internal
    Namespace:     cilium
    Section Name:  http-solver
  Rules:
    Backend Refs:
      Group:   
      Kind:    Service
      Name:    hello-world
      Port:    80
      Weight:  1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
Status:
  Parents:
    Conditions:
      Last Transition Time:  2024-12-20T16:39:38Z
      Message:               Accepted HTTPRoute
      Observed Generation:   1
      Reason:                Accepted
      Status:                True
      Type:                  Accepted
      Last Transition Time:  2024-12-20T16:39:38Z
      Message:               Service reference is valid
      Observed Generation:   1
      Reason:                ResolvedRefs
      Status:                True
      Type:                  ResolvedRefs
    Controller Name:         io.cilium/gateway-controller
    Parent Ref:
      Group:         gateway.networking.k8s.io
      Kind:          Gateway
      Name:          internal
      Namespace:     cilium
      Section Name:  http-solver
Events:              <none>
```

4. add HTTPS listener to the gateway

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: cilium
spec:
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 10.10.0.33
  gatewayClassName: cilium
  listeners:
  - name: http-solver
    protocol: HTTP
    port: 80
    allowedRoutes:
        namespaces:
          from: All
  - name: hello-world
    protocol: HTTPS
    port: 443
    hostname: "hello-world.onprem.internal"
    tls:
      certificateRefs:
      - group: ''
        kind: Secret
        name: hello-world-internal
    allowedRoutes:
      namespaces:
        from: All
```

5. check if service on http is still working as expected

```shell
curl -I http://hello-world.onprem.internal 
                                   
HTTP/1.1 404 Not Found
date: Fri, 20 Dec 2024 17:27:39 GMT
server: envoy
transfer-encoding: chunked
```

check cilium-envoy pod logs:

> [2024-12-20 17:29:30.048][76][trace][filter] [external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:106] tls inspector: new connection accepted
[2024-12-20 17:29:30.048][76][trace][misc] [external/envoy/source/common/network/tcp_listener_impl.cc:114] TcpListener accepted 1 new connections.
[2024-12-20 17:29:30.048][76][trace][filter] [external/envoy/source/common/network/listener_filter_buffer_impl.cc:95] onFileEvent: 1
[2024-12-20 17:29:30.048][76][trace][filter] [external/envoy/source/common/network/listener_filter_buffer_impl.cc:60] recv returned: 0
[2024-12-20 17:29:30.048][76][trace][filter] [external/envoy/source/common/network/listener_filter_buffer_impl.cc:64] recv return try again
[2024-12-20 17:29:30.048][76][trace][filter] [external/envoy/source/common/network/listener_filter_buffer_impl.cc:95] onFileEvent: 1
[2024-12-20 17:29:30.048][76][trace][filter] [external/envoy/source/common/network/listener_filter_buffer_impl.cc:60] recv returned: 91
[2024-12-20 17:29:30.048][76][trace][filter] [external/envoy/source/extensions/filters/listener/tls_inspector/tls_inspector.cc:146] tls inspector: recv: 91
[2024-12-20 17:29:30.048][76][debug][misc] [cilium/bpf_metadata.cc:305] EGRESS POD IP: 10.20.254.178, destination IP: 10.10.0.33 sni: ""
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/conntrack.cc:178] cilium.bpf_metadata: Using conntrack map global
[2024-12-20 17:29:30.048][76][trace][filter] [cilium/conntrack.cc:197] cilium.bpf_metadata: Looking up key: a0a0021, a14feb2, 50, c797, 6, 0
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/conntrack.cc:128] cilium.bpf_metadata: Opened IPv4 conntrack map global
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/conntrack.cc:229] cilium.bpf_metadata: IPv4 conntrack map global lookup failed: No such file or directory
[2024-12-20 17:29:30.048][76][trace][filter] [cilium/ipcache.cc:102] cilium.ipcache: Looking up key: a14feb2, prefixlen: 32
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/ipcache.cc:110] cilium.ipcache: 10.20.254.178 has ID 2
[2024-12-20 17:29:30.048][76][trace][filter] [cilium/ipcache.cc:102] cilium.ipcache: Looking up key: a0a0021, prefixlen: 32
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/ipcache.cc:110] cilium.ipcache: 10.10.0.33 has ID 2
[2024-12-20 17:29:30.048][76][trace][filter] [cilium/ipcache.cc:102] cilium.ipcache: Looking up key: a2a0080, prefixlen: 32
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/ipcache.cc:110] cilium.ipcache: 10.42.0.128 has ID 8
[2024-12-20 17:29:30.048][76][debug][filter] [./cilium/socket_option.h:246] Cilium SocketOption(): source_identity: 8, ingress: false, port: 80, pod_ip: 10.42.0.128, source_addresses: /10.42.0.128:0/, mark: 80b00 (magic mark: b00, cluster: 0, ID: 8), proxy_id: 11889, sni: ""
[2024-12-20 17:29:30.048][76][trace][misc] [external/envoy/source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x1667fe95e000 for 3600000ms, min is 3600000ms
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/network_filter.cc:77] cilium.network: onNewConnection
[2024-12-20 17:29:30.048][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:474] [Tags: "ConnectionId":"574"] raising connection event 2
[2024-12-20 17:29:30.048][76][debug][conn_handler] [external/envoy/source/common/listener_manager/active_tcp_listener.cc:160] [Tags: "ConnectionId":"574"] new connection from 10.20.254.178:51095
[2024-12-20 17:29:30.048][76][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:228] item added to deferred deletion list (size=1)
[2024-12-20 17:29:30.048][76][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:122] clearing deferred deletion list (size=1)
[2024-12-20 17:29:30.048][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:619] [Tags: "ConnectionId":"574"] socket event: 3
[2024-12-20 17:29:30.048][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:742] [Tags: "ConnectionId":"574"] write ready
[2024-12-20 17:29:30.048][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:659] [Tags: "ConnectionId":"574"] read ready. dispatch_buffered_data=0
[2024-12-20 17:29:30.048][76][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:25] [Tags: "ConnectionId":"574"] read returns: 91
[2024-12-20 17:29:30.048][76][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:39] [Tags: "ConnectionId":"574"] read error: Resource temporarily unavailable, code: 0
[2024-12-20 17:29:30.048][76][trace][filter] [cilium/network_filter.cc:202] cilium.network: onData 91 bytes, end_stream: false
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:646] [Tags: "ConnectionId":"574"] parsing 91 bytes
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:588] [Tags: "ConnectionId":"574"] message begin
[2024-12-20 17:29:30.048][76][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:398] [Tags: "ConnectionId":"574"] new stream
[2024-12-20 17:29:30.048][76][trace][misc] [external/envoy/source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x1667fea24540 for 300000ms, min is 300000ms
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:545] [Tags: "ConnectionId":"574"] completed header: key=Host value=hello-world.onprem.internal
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:545] [Tags: "ConnectionId":"574"] completed header: key=User-Agent value=curl/8.7.1
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:839] [Tags: "ConnectionId":"574"] onHeadersCompleteImpl
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:545] [Tags: "ConnectionId":"574"] completed header: key=Accept value=*/*
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:1192] [Tags: "ConnectionId":"574"] Server: onHeadersComplete size=3
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:943] [Tags: "ConnectionId":"574"] message complete
[2024-12-20 17:29:30.048][76][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1147] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] request headers complete (end_stream=true):
':authority', 'hello-world.onprem.internal'
':path', '/'
':method', 'HEAD'
'user-agent', 'curl/8.7.1'
'accept', '*/*'
[2024-12-20 17:29:30.048][76][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1130] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] request end stream
[2024-12-20 17:29:30.048][76][debug][connection] [external/envoy/source/common/network/connection_impl.h:98] [Tags: "ConnectionId":"574"] current connecting state: false
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:603] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] decode headers called: filter=envoy.filters.http.grpc_web status=0
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:603] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] decode headers called: filter=envoy.filters.http.grpc_stats status=0
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/l7policy.cc:135] cilium.l7policy: downstream decodeHeaders()
[2024-12-20 17:29:30.048][76][trace][filter] [cilium/ipcache.cc:102] cilium.ipcache: Looking up key: a0a0021, prefixlen: 32
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/ipcache.cc:110] cilium.ipcache: 10.10.0.33 has ID 2
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/l7policy.cc:200] cilium.l7policy: Ingress from 2 policy lookup for endpoint 10.42.0.128 for port 80: ALLOW
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:603] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] decode headers called: filter=cilium.l7policy status=0
[2024-12-20 17:29:30.048][76][debug][router] [external/envoy/source/common/router/router.cc:447] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] no route match for URL '/'
[2024-12-20 17:29:30.048][76][debug][http] [external/envoy/source/common/http/filter_manager.cc:1027] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] Preparing local reply with details route_not_found
[2024-12-20 17:29:30.048][76][debug][http] [external/envoy/source/common/http/filter_manager.cc:1069] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] Executing sending local reply.
[2024-12-20 17:29:30.048][76][trace][misc] [external/envoy/source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x1667fea24540 for 300000ms, min is 300000ms
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:907] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] commonEncodePrefix end_stream: true, isHalfCloseEnabled: false
[2024-12-20 17:29:30.048][76][debug][filter] [cilium/l7policy.cc:246] cilium.l7policy: downstream encodeHeaders()
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:1245] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] encode headers called: filter=cilium.l7policy status=0
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:1245] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] encode headers called: filter=envoy.filters.http.grpc_stats status=0
[2024-12-20 17:29:30.048][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:1245] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] encode headers called: filter=envoy.filters.http.grpc_web status=0
[2024-12-20 17:29:30.048][76][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1838] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Fri, 20 Dec 2024 17:29:29 GMT'
'server', 'envoy'
[2024-12-20 17:29:30.049][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:534] [Tags: "ConnectionId":"574"] writing 106 bytes, end_stream false
[2024-12-20 17:29:30.049][76][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1950] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] Codec completed encoding stream.
[2024-12-20 17:29:30.049][76][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:228] item added to deferred deletion list (size=1)
[2024-12-20 17:29:30.049][76][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:228] item added to deferred deletion list (size=2)
[2024-12-20 17:29:30.049][76][trace][misc] [external/envoy/source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x1667fe95e000 for 3600000ms, min is 3600000ms
[2024-12-20 17:29:30.049][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:594] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] decodeHeaders filter iteration aborted due to local reply: filter=envoy.filters.http.router
[2024-12-20 17:29:30.049][76][trace][http] [external/envoy/source/common/http/filter_manager.cc:603] [Tags: "ConnectionId":"574","StreamId":"17226087540785556413"] decode headers called: filter=envoy.filters.http.router status=1
[2024-12-20 17:29:30.049][76][trace][http] [external/envoy/source/common/http/http1/codec_impl.cc:696] [Tags: "ConnectionId":"574"] parsed 91 bytes
[2024-12-20 17:29:30.049][76][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:122] clearing deferred deletion list (size=2)
[2024-12-20 17:29:30.049][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:619] [Tags: "ConnectionId":"574"] socket event: 2
[2024-12-20 17:29:30.049][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:742] [Tags: "ConnectionId":"574"] write ready
[2024-12-20 17:29:30.049][76][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:70] [Tags: "ConnectionId":"574"] write returns: 106
[2024-12-20 17:29:30.061][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:619] [Tags: "ConnectionId":"574"] socket event: 3
[2024-12-20 17:29:30.061][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:742] [Tags: "ConnectionId":"574"] write ready
[2024-12-20 17:29:30.061][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:659] [Tags: "ConnectionId":"574"] read ready. dispatch_buffered_data=0
[2024-12-20 17:29:30.061][76][trace][connection] [external/envoy/source/common/network/raw_buffer_socket.cc:25] [Tags: "ConnectionId":"574"] read returns: 0
[2024-12-20 17:29:30.061][76][debug][connection] [external/envoy/source/common/network/connection_impl.cc:719] [Tags: "ConnectionId":"574"] remote close
[2024-12-20 17:29:30.061][76][debug][connection] [external/envoy/source/common/network/connection_impl.cc:281] [Tags: "ConnectionId":"574"] closing socket: 0
[2024-12-20 17:29:30.075][76][trace][connection] [external/envoy/source/common/network/connection_impl.cc:474] [Tags: "ConnectionId":"574"] raising connection event 0
[2024-12-20 17:29:30.075][76][trace][conn_handler] [external/envoy/source/common/listener_manager/active_stream_listener_base.cc:126] [Tags: "ConnectionId":"574"] tcp connection on event 0
[2024-12-20 17:29:30.075][76][debug][conn_handler] [external/envoy/source/common/listener_manager/active_stream_listener_base.cc:136] [Tags: "ConnectionId":"574"] adding to cleanup list
[2024-12-20 17:29:30.075][76][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:228] item added to deferred deletion list (size=1)
[2024-12-20 17:29:30.075][76][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:228] item added to deferred deletion list (size=2)
[2024-12-20 17:29:30.075][76][trace][main] [external/envoy/source/common/event/dispatcher_impl.cc:122] clearing deferred deletion list (size=2)
