### ISSUE TITLE
"cilium install" uses images with incorrect "None/cilium/cilium" repository on kcli cluster

### ISSUE THREAD

**Issue by ldoktor** [cilium/cilium-cli#3001]
## Bug report

Hello folks, I'm trying to deploy a testing kubernetes with cilium using kcli tool. What it does is it uses ubuntu 22.04, runs kubeadm to create kubernetes, then it downloads and installs cilium by:

```
curl -LO https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
rm -f cilium-linux-amd64.tar.gz
cilium install
```

which reports:

```
Using Cilium version 1.17.0
🔮 Auto-detected cluster name: peer-pods
🔮 Auto-detected kube-proxy has been installed
```

But the outcome is that all cilium images are prefixed by `None/` (eg. `None/cilium/cilium-envoy`). I tried running update manually with various versions and repositories with the same results. For example following shows:

```
cilium upgrade --version 1.17.0 --dry-run-helm-values --repository https://helm.cilium.io --helm-set=image.repository=quay.io/cilium/cilium
cluster:
  name: peer-pods
envoy:
  image:
    repository: None/cilium/cilium-envoy
    tag: latest
    useDigest: false
image:
  repository: quay.io/cilium/cilium
  useDigest: false
operator:
  image:
    repository: None/cilium/operator
    useDigest: false
  replicas: 1
routingMode: tunnel
tunnelProtocol: vxlan
```

it for some reason insists on `None/`. Trying to install via helm works well:

```
root@peer-pods-ctlplane-0:~# helm repo add cilium https://helm.cilium.io
"cilium" has been added to your repositories
root@peer-pods-ctlplane-0:~# helm upgrade --install cilium cilium/cilium \
    --namespace kube-system \
    --set image.repository=quay.io/cilium/cilium
Release "cilium" has been upgraded. Happy Helming!
NAME: cilium
LAST DEPLOYED: Thu Apr  3 09:59:05 2025
NAMESPACE: kube-system
STATUS: deployed
REVISION: 5
TEST SUITE: None
NOTES:
You have successfully installed Cilium with Hubble.

Your release version is 1.17.2.

For any further help, visit https://docs.cilium.io/en/v1.17/gettinghelp
```

**General Information**

- Cilium CLI version: various versions 1.16-1.18
- Orchestration system version in use:

    Client Version: v1.30.0
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.30.0

- Platform / infrastructure information: kcli
- Generate and upload a system zip: N/A (incorrect image)

**How to reproduce the issue**

1. kcli create kube generic -P domain=kata.com -P pool=default -P ctlplanes=1 -P workers=1 -P network=default -P image=ubuntu2204 -P sdn=cilium -P nfs=false -P disk_size=20 -P version=1.30.0 -P engine=crio peer-pods
2. wait for it to fail, the `kubectl get all -n kube-system` reports Image errors (one can use `kcli ssh peer-pods-ctlplane-0` to get on the machine)
