### ISSUE TITLE
cluster name can not match Regular expressions

### ISSUE THREAD

**Issue by mengxifl** [cilium/cilium-cli#459]
here is my k8sinit.yaml file 
kubeadm init --skip-phases=addon/kube-proxy  --config=k8sinit.yaml 
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.130.147.42
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.20.0
etcd:
  external:
    endpoints:
    - "https://10.130.147.42:2379"
    - "https://10.130.147.43:2379" 
    - "https://10.130.147.44:2379"
    caFile: /etc/kubernetes/pki/etcd/ca.pem
    certFile: /etc/kubernetes/pki/etcd/client.pem
    keyFile: /etc/kubernetes/pki/etcd/client-key.pem
networking:
  podSubnet: 10.120.0.0/17
  serviceSubnet: 10.120.128.0/17
apiServer:
  certSANs: [k8smaster00,k8smaster01,10.130.147.42,10.130.147.43,127.0.0.1]
  extraArgs:
    service-node-port-range: 20-65535
clusterName: "kubenetesCluster"
controlPlaneEndpoint: 10.130.147.45:6443
```
here is my setting of clusterName 
```
clusterName: "kubenetesCluster"
```
when I use command
`cilium install`

give me  an error  mean cluster name can not match Regular expressions

This regular expression setting is too strict I think
