### ISSUE TITLE
install command doesn't create metric services

### ISSUE THREAD

**Issue by michi-covalent** [cilium/cilium-cli#947]
i installed cilium with this values file:
```
hubble:
  metrics:
    enabled:
    - flow
prometheus:
  enabled: true
```

`cilium install --version v1.12.0-rc3 --helm-values ./values.yaml` doesn't create `cilium-agent` / `hubble-metrics` services.
